apiVersion: deployments.plural.sh/v1alpha1
kind: Cluster
metadata:
  name: existing
  namespace: default
spec:
  handle: lukasz
---
apiVersion: deployments.plural.sh/v1alpha1
kind: GitRepository
metadata:
  name: guestbook
  namespace: default
  annotations:
    config.kubernetes.io/depends-on: /namespaces/default/Cluster/existing
spec:
  url: https://github.com/argoproj/argocd-example-apps.git
---
---
apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: guestbook
  namespace: default
  annotations:
    config.kubernetes.io/depends-on: /namespaces/default/GitRepository/guestbook
spec:
  git:
    folder: guestbook
    ref: master
  repositoryRef:
    kind: GitRepository
    name: guestbook
    namespace: default
  clusterRef:
    kind: Cluster
    name: existing
    namespace: default
---
apiVersion: deployments.plural.sh/v1alpha1
kind: GlobalService
metadata:
  name: globalservice-guestbook
  namespace: default
  annotations:
    config.kubernetes.io/depends-on: /namespaces/default/ServiceDeployment/guestbook
spec:
  serviceRef:
    name: guestbook
    namespace: default
